### ISSUE TITLE
1.21 Update

### ISSUE THREAD

**Issue by DreamLoveNing** [Nyan-Work/plusls-carpet-addition#31] opened 2024-07-18 07:17 UTC
### What new features do you want?

Please update 1.21 version plz

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Hendrix-Shen** [comment] 2024-07-20 08:15
Duplicate of #28

**Closed by Hendrix-Shen** 2024-07-20 08:15 UTC
Labels: resolution: duplicate, type: enhancement
