### ISSUE TITLE
[Feature Request] Update to 1.21 Please

### ISSUE THREAD

**Issue by Grayer0113** [Nyan-Work/plusls-carpet-addition#29] opened 2024-06-19 13:41 UTC
### What new features do you want?

Update to 1.21

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Hendrix-Shen** [comment] 2024-07-20 08:14
Duplicate of #28

**Closed as not planned by Hendrix-Shen** 2024-07-20 08:14 UTC
Labels: resolution: duplicate, type: enhancement
